# Generated by Django 3.0.5 on 2020-05-22 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='app',
            name='testing_instructions',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('tag', models.CharField(choices=[('E', 'Enhancement'), ('B', 'Bug'), ('U', 'UI/UX')], default='B', max_length=1)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bugtracker.App')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_assigned', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
