# Generated by Django 3.0.5 on 2020-05-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0003_auto_20200522_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bug',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bugtracker.App'),
        ),
    ]
