# Generated by Django 3.0.5 on 2020-05-22 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0004_auto_20200522_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='team_members',
            field=models.ManyToManyField(related_name='apps_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bugtracker.App'),
        ),
    ]
